baseurl = "https://mydatavoyage.rbind.io/"
title = "My Data Voyage"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "&copy; 2017 Mayank Bhushan"
enableEmoji = true
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "Mayank Bhushan"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "My Data Voyage"
    description = ""
    github = "https://github.com/mayank634"
    linkedin = "https://linkedin.com/in/mayank634/"
    twitter = "https://twitter.com/mayank634"
    email = "mayank634@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
