baseurl = "https://mydatavoyage.rbind.io/"
title = "My Data Voyage"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "&copy; 2017 Mayank Bhushan"
enableEmoji = true
disableKinds = ["RSS"]
disableRSS = true

[Author]
    name = "Mayank Bhushan"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "My Data Voyage"
    description = ""
    github = "https://github.com/mayank634"
    linkedin = "https://linkedin.com/in/mayank634/"
    twitter = "https://twitter.com/mayank634"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
